version: '3'

services:
  postgres:
    image: 'postgres:15.2'
    environment:
      - POSTGRES_DB=ping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "15432:5432"
  ping:
    build:
      dockerfile: Dockerfile
    image: ping-backend:0.0.1
    container_name: ping-backend
    depends_on:
      - postgres
    ports:
      - "9000:8080"
    environment:
      - POSTGRES_URL=host.docker.internal:15432/ping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
