server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: ping
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5433/ping}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    open-in-view: false
